sonar.projectKey=Xmarcelo05_ParkingWeb
sonar.organization=xmarcelo05
sonar.host.url=https://sonarcloud.io
sonar.token=afd0e6880e9ac829d6bf447826ec6c4e3c35bcc5

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=ParkingWeb
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8