sonar.projectKey=Xmarcelo05_ParkingWeb
sonar.organization=xmarcelo05
sonar.host.url=https://sonarcloud.io

# Nombres y versión del proyecto
sonar.projectName=ParkingWeb
sonar.projectVersion=1.0

# Archivos a escanear (Se quitó el #)
sonar.sources=.
sonar.exclusions=node_modules/**, .svelte-kit/**, dist/**

# Codificación
sonar.sourceEncoding=UTF-8